#!/bin/bash

# Get the dir of the current script
script_dir="$( cd "$( dirname "$0" )" && pwd )"

mkdir -p ~/bin
ln -s $script_dir/scripts/mr ~/bin
ln -s $script_dir/scripts/ssha ~/bin
sudo ln -s $script_dir/slim.conf /etc/
sudo ln -s $script_dir/slimlock.conf /etc/
sudo ln -s $script_dir/05-keyboard-layout.conf /etc/X11/xorg.conf.d/
sudo ln -s $script_dir/20-nvidia.conf /etc/X11/xorg.conf.d/
sudo ln -s $script_dir/makepkg.conf /etc
sudo ln -s $script_dir/locale.conf /etc
sudo ln -s $script_dir/mirrorlist /etc/pacman.d/
ln -s $script_dir/xinitrc ~/.xinitrc
ln -s $script_dir/Xdefaults ~/.Xdefaults
ln -s $script_dir/zshrc ~/.zshrc
ln -s $script_dir/shell_aliases ~/.shell_aliases
ln -s $script_dir/vimrc ~/.vimrc
ln -s $script_dir/gitconfig ~/.gitconfig
ln -s $script_dir/gitignore_global ~/.gitignore_global
ln -s $script_dir/tmux.conf ~/.tmux.conf
ln -s $script_dir/gtkrc-2.0.mine ~/.gtkrc-2.0.mine
ln -s $script_dir/user-dirs.dirs ~/.config/
ln -s $script_dir/mimeapps.list ~/.local/share/applications/
ln -s $script_dir/config/awesome ~/.config/
ln -s $script_dir/config/redshift.conf ~/.config/
ln -s $script_dir/config/pcmanfm.conf ~/.config/pcmanfm/default/
ln -s $script_dir/config/rediotray.xml ~/.local/share/radiotray/bookmarks.xml
